version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    networks:
      - backend
  search:
    image: elasticsearch:latest
    environment:
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - backend
  redis:
    image: redis
    networks:
      - backend
  web:
    build: .
    command: ./bin/rails server
    volumes:
      - .:/channel-api
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - search
    networks:
      - backend
  cable:
    build: .
    command: ./bin/cable
    volumes:
      - .:/channel-api
    ports:
      - "28080:28080"
    depends_on:
      - db
      - redis
      - search
    networks:
      - backend
  worker:
    build: .
    command: sidekiq
    volumes:
      - .:/channel-api
    depends_on:
      - db
      - redis
      - search
      - cable
    networks:
      - backend
  harvester:
    build: ./harvester
    volumes:
      - ./harvester:/harvester
    depends_on:
      - web
      - cable
    networks:
      - backend
networks:
  backend:
    driver: bridge
